# Generated by Django 6.0.5 on 2026-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficrecord",
            options={"ordering": ["date", "time", "id"]},
        ),
        migrations.AlterField(
            model_name="trafficrecord",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Medium", "Medium"),
                    ("Heavy", "Heavy"),
                    ("Very Heavy", "Very Heavy"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trafficrecord",
            name="vehicle_count",
            field=models.PositiveIntegerField(),
        ),
    ]
